<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="d7e6deb3-1a12-4cb1-82e9-f173151f8855" name="Javi@JAVI-PC 2010-09-19 13:26:50" runUser="Javi-PC\Javi" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="da34d0b4-0511-46eb-bb91-669de211e68e">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment userDeploymentRoot="C:\Code\WcfHttpAuth\TestResults" useDefaultDeploymentRoot="false" enabled="false" runDeploymentRoot="Javi_JAVI-PC 2010-09-19 13_26_50">
      <DeploymentItem filename="C:\Code\WcfHttpAuth\WcfHttpAuth\bin\Debug\WcfHttpAuth.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2010-09-19T13:26:50.9624274+02:00" queuing="2010-09-19T13:26:52.8125332+02:00" start="2010-09-19T13:26:53.0045442+02:00" finish="2010-09-19T13:27:07.9513991+02:00" />
  <ResultSummary outcome="Error">
    <Counters total="1" executed="1" error="0" failed="0" timeout="0" aborted="1" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
    <RunInfos>
      <RunInfo computerName="JAVI-PC" outcome="Error" timestamp="2010-09-19T13:27:07.9473989+02:00">
        <Text>Test host process exited unexpectedly.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="Given_credentials_are_valid_then_should_return_200" storage="c:\code\wcfhttpauth\wcfhttpauth.integrationtests\bin\debug\wcfhttpauth.integrationtests.dll" id="d2c4f2ed-2807-a47b-bc9e-9a4b6401e12e">
      <Execution id="18918605-32d2-4ee0-b17d-ba7a0357db2b" />
      <TestMethod codeBase="C:/Code/WcfHttpAuth/WcfHttpAuth.IntegrationTests/bin/Debug/WcfHttpAuth.IntegrationTests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="WcfHttpAuth.IntegrationTests.When_calling_a_basic_auth_service, WcfHttpAuth.IntegrationTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="Given_credentials_are_valid_then_should_return_200" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="d2c4f2ed-2807-a47b-bc9e-9a4b6401e12e" executionId="18918605-32d2-4ee0-b17d-ba7a0357db2b" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="18918605-32d2-4ee0-b17d-ba7a0357db2b" testId="d2c4f2ed-2807-a47b-bc9e-9a4b6401e12e" testName="Given_credentials_are_valid_then_should_return_200" computerName="JAVI-PC" duration="00:00:14.7778452" startTime="2010-09-19T13:26:53.1735539+02:00" endTime="2010-09-19T13:27:07.9513991+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Aborted" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="18918605-32d2-4ee0-b17d-ba7a0357db2b">
    </UnitTestResult>
  </Results>
</TestRun>